# Generated by Django 3.2.6 on 2021-09-06 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210819_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='is_notified',
            field=models.BooleanField(default=False),
        ),
    ]
