# Generated by Django 3.2.6 on 2021-09-20 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_author_is_notified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['pub_date']},
        ),
    ]
